name: Build .bin Book

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install chess requests

    - name: Fetch games and build PGN
      run: python fetch_and_build.py

    - name: Create Polyglot book
      run: |
        chmod +x ./engines/fairy-stockfish_x86-64-bmi2
        ./engines/fairy-stockfish_x86-64-bmi2 makebook \
          format=polyglot \
          infile=filtered_960_bots_2200plus.pgn \
          outfile=book.bin \
          depth=16 \
          max-ply=32


    - name: Move .bin to engines/
      run: |
        mkdir -p engines
        mv book.bin engines/

    - name: Upload book.bin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: chess960-opening-book
        path: engines/book.bin
