name: Fetch & Build Chess960 Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests python-chess

    - name: Fetch games (PGN)
      run: python fetch_and_build.py

    - name: Build Polyglot book
      run: python create_polyglot.py

    - name: Move book if exists
      run: |
        mkdir -p engines
        if [ -f book.bin ]; then
          mv book.bin engines/filtered_960_bots_2200plus.bin
        else
          echo "❌ book.bin not found. Skipping move."
          exit 1
        fi

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: polyglot-book
        path: engines/filtered_960_bots_2200plus.bin

    - name: Commit and push updated book
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git pull origin "${GITHUB_REF_NAME}" --rebase || true
        git add engines/filtered_960_bots_2200plus.bin
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update Chess960 opening book"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD
