name: Build Antichess Book

on:
  workflow_dispatch:    

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y g++ make zstd wget

      - name: Download latest Antichess PGN.zst
        run: |
          wget -O antichess.pgn.zst https://database.lichess.org/antichess/lichess_db_antichess_rated_2025-07.pgn.zst
          unzstd antichess.pgn.zst -o antichess.pgn

      - name: Compile Polyglot
        run: |
          git clone https://github.com/ddugovic/polyglot.git
          cd polyglot
          make
          cp polyglot ../polyglot

      - name: Run filter + build
        run: python3 filter_and_build.py

      - name: Upload book.bin
        uses: actions/upload-artifact@v4
        with:
          name: antichess-book
          path: book.bin
