name: Build Antichess Opening Book

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd wget gcc make python3

      - name: Fetch latest list of files
        run: |
          wget -O antichess_list.txt https://database.lichess.org/antichess/list.txt

      - name: Set latest PGN ZST URL and download
        id: download
        run: |
          LATEST=$(tail -n 1 antichess_list.txt)
          echo "latest_file=$LATEST" >> $GITHUB_OUTPUT
          wget -O antichess.pgn.zst https://database.lichess.org/antichess/$LATEST
          zstd -d antichess.pgn.zst -o antichess_all.pgn

      - name: Run filter_and_build.py
        run: |
          python3 filter_and_build.py antichess_all.pgn antichess_book.bin --min-elo 2800 --max-ply 50

      - name: Upload Book
        uses: actions/upload-artifact@v4
        with:
          name: antichess_book
          path: antichess_book.bin
