name: build-crazyhouse-book

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make

      - name: Compile bookbuilder
        run: g++ -O3 -o bookbuilder book_make.cpp polyglot/*.cpp

      - name: Run script
        run: python filter_and_build.py

      - name: Upload book
        uses: actions/upload-artifact@v4
        with:
          name: crazyhouse-book
          path: book.bin
