name: Fetch & Build Chess960 Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with: python-version: '3.11'

    - name: Install Dependencies
      run: pip install requests python-chess

    - name: Fetch games & build book
      run: python fetch_and_build.py

    - name: Move book.bin to engines
      run: |
        mkdir -p engines
        mv book.bin engines/filtered_960_bots_2200plus.bin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: polyglot-book
        path: engines/filtered_960_bots_2200plus.bin

    - name: Commit and push book.bin
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git pull origin ${{ github.ref_name }} --rebase
        git add engines/filtered_960_bots_2200plus.bin
        if git diff --cached --quiet; then
          echo "No changes in book"
        else
          git commit -m "Update Chess960 book"
          git push https://${{ env.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
        fi
