name: Build .bin Book

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Fetch games and build PGN
      run: python fetch_and_build.py

    - name: Build Fairy-Stockfish
      run: |
        git clone https://github.com/fairy-stockfish/Fairy-Stockfish.git
        cd Fairy-Stockfish/src
        make build ARCH=x86-64-modern
        cd ../..

    - name: Create Antichess Polyglot book
      run: |
        ./Fairy-Stockfish/src/fairy-stockfish makebook \
          -pgn filtered_960_bots_2200plus.pgn \
          -bin book.bin \
          -max-ply 20 -quiet

    - name: Move .bin to engines/
      run: |
        mkdir -p engines
        mv book.bin engines/

    - name: Upload book.bin as artifact
      uses: actions/upload-artifact@v4
      with:
        name: antichess-opening-book
        path: engines/book.bin
