name: Build .bin Book

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install chess requests

    - name: Fetch games and build PGN
      run: python fetch_and_build.py

    - name: Create Polyglot book
      run: python create_polyglot.py

    - name: Move .bin to engines/
      run: |
        mkdir -p engines
        mv book.bin engines/

    - name: Commit and push updated book
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        git stash --include-untracked || true
        git pull origin "${GITHUB_REF_NAME}" --rebase || true
        git stash pop || true

        git add engines/book.bin

        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "Update Chess960 opening book"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD
        fi
