name: Build Antichess Book (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install chess requests

      - name: Fetch games + build anti book
        run: python filter_and_build.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: antichess-book
          path: |
            antichess_games.pgn
            anti_book.bin
