name: Build Antichess Opening Book

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd gcc make wget python3

      - name: Get latest Antichess PGN URL
        run: |
          wget -O antichess_list.txt https://database.lichess.org/antichess/list.txt
          LATEST=$(tail -n 1 antichess_list.txt)
          if [[ "$LATEST" == http* ]]; then
            URL="$LATEST"
          else
            URL="https://database.lichess.org/antichess/$LATEST"
          fi
          echo "LATEST_URL=$URL" >> $GITHUB_ENV

      - name: Download and extract PGN
        run: |
          echo "Downloading $LATEST_URL"
          wget -O antichess.pgn.zst "$LATEST_URL"
          zstd -d antichess.pgn.zst -o antichess_all.pgn

      - name: Run filter_and_build.py
        run: |
          python3 filter_and_build.py antichess_all.pgn antichess_book.bin --min-elo 2800 --max-ply 50

      - name: Upload Book
        uses: actions/upload-artifact@v4
        with:
          name: antichess_book
          path: antichess_book.bin
