name: Build Crazyhouse Book

on:
  workflow_dispatch:
  push:
    paths:
      - filter_and_build.py
      - .github/workflows/crazyhouse-book.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Build Crazyhouse Opening Book
        run: |
          python filter_and_build.py

      - name: Upload book artifact
        uses: actions/upload-artifact@v4
        with:
          name: crazyhouse_book
          path: crazyhouse_book.bin
