name: Build .bin Book

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install python-chess
      run: pip install chess

    - name: Build .bin from PGN
      run: python create_polyglot.py

    - name: Move bin to engines/
      run: |
        mkdir -p engines
        mv filtered_960_bots_2200plus.bin engines/

    - name: Commit and push updated book
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

        # Temporarily stash any uncommitted changes (like PGN/bin)
        git stash --include-untracked

        # Safely pull latest changes from the branch
        git pull origin "${GITHUB_REF_NAME}" --rebase || true

        # Restore stashed files
        git stash pop || true

        # Stage only the .bin file
        git add engines/filtered_960_bots_2200plus.bin

        # Commit and push if anything changed
        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "Update Chess960 opening book"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD
        fi
