name: Find best config

on:
  workflow_dispatch:

jobs:
  find-best:
    runs-on: ubuntu-latest

    steps:
      - name: clone realboy’s repo
        run: git clone --depth 1 https://github.com/zonalraid45/Mypant.git

      - name: find the best config (4219–8000)
        run: |
          cd Mypant/Config
          sha256sum config{4219..8000}.yml | sort | uniq -u -w64 | awk '{print $2}'
