name: Find Real Config from Friend’s Repo

on:
  workflow_dispatch:

jobs:
  find-unique-config:
    runs-on: ubuntu-latest

    steps:
      - name: Clone friend’s repo
        run: git clone --depth 1 https://github.com/zonalraid45/Mypant.git

      - name: Find the real config (4219–8000)
        run: |
          cd Mypant/Config
          sha256sum config{4219..8000}.yml | sort | uniq -u -w64 | awk '{print $2}'
