name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Clone Polyglot (dukegod fork with Makefile)
      run: |
        git clone https://github.com/dukegod/polyglot.git
        cd polyglot
        make

    - name: Make Polyglot Book
      run: |
        ./polyglot/polyglot make-book filtered_960_bots_2200plus.pgn book.bin 40 16

    - name: Upload book.bin
      uses: actions/upload-artifact@v4
      with:
        name: chess960-book
        path: book.bin
