name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Clone ddugovic/polyglot and build
      run: |
        git clone https://github.com/ddugovic/polyglot.git
        cd polyglot/src
        make

    - name: Generate Polyglot book
      run: |
        ./polyglot/src/polyglot make-book \
          -pgn filtered_960_bots_2200plus.pgn \
          -bin book.bin \
          -max-ply 40 \
          -threads 16

    - name: Upload generated book
      uses: actions/upload-artifact@v4
      with:
        name: polyglot-book
        path: book.bin
