name: Build and Push Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libleveldb-dev

    - name: Clone Polyglot (sshivaji)
      run: git clone https://github.com/sshivaji/polyglot.git

    - name: Build Polyglot
      run: |
        cd polyglot/src
        make

    - name: Generate book.bin in engines/
      run: |
        mkdir -p engines
        polyglot/src/polyglot make-book \
          filtered_960_bots_2200plus.pgn \
          engines/book.bin \
          40 16

    - name: Commit and push book.bin
      run: |
        git add engines/book.bin
        git commit -m "Add updated book.bin"
        git push
      env:
        GIT_AUTHOR_NAME: github-actions[bot]
        GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
        GIT_COMMITTER_NAME: github-actions[bot]
        GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
