name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Clone Polyglot (correct branch and folder)
      run: |
        git clone https://github.com/ddugovic/polyglot.git
        cd polyglot/src/polyglot
        make

    - name: Make Book
      run: |
        ./polyglot/src/polyglot/polyglot make-book \
          -pgn filtered_960_bots_2200plus.pgn \
          -bin book.bin \
          -max-ply 40 \
          -threads 16

    - name: Upload .bin file
      uses: actions/upload-artifact@v4
      with:
        name: chess960-book
        path: book.bin
