name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libleveldb-dev

    - name: Clone working Polyglot repo
      run: |
        git clone https://github.com/sshivaji/polyglot.git
        cd polyglot/src
        make

    - name: Generate book.bin
      run: |
        ./polyglot/src/bookbuilder filtered_960_bots_2200plus.pgn book.bin 40 16

    - name: Commit and push book.bin to engines/
      run: |
        cp book.bin engines/
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add engines/book.bin
        git commit -m "Add built book.bin"
        git push
