name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libleveldb-dev

    - name: Clone working Polyglot repo
      run: |
        git clone https://github.com/sshivaji/polyglot.git
        cd polyglot/src
        make

    - name: Build book.bin
      run: |
        ./polyglot/src/make-book filtered_960_bots_2200plus.pgn book.bin 40 16
        mkdir -p engines
        mv book.bin engines/book.bin

    - name: Commit and push book.bin to engines/
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git pull origin ${{ github.ref_name }}
        git add engines/book.bin

        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Add generated book.bin to engines folder"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
        fi
