name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Clone Carek Polyglot repo
      run: |
        git clone https://github.com/carek14/polyglot.git
        cd polyglot
        make

    - name: Generate book.bin
      run: |
        ./polyglot/polyglot make-book \
          --pgn filtered_960_bots_2200plus.pgn \
          --bin book.bin \
          --max-ply 40

    - name: Upload book.bin
      uses: actions/upload-artifact@v4
      with:
        name: chess960-book
        path: book.bin
