name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake

    - name: Clone Polyglot (ddugovic fork)
      run: |
        git clone https://github.com/ddugovic/polyglot.git

    - name: Build Polyglot
      run: |
        cd polyglot
        autoreconf -i
        ./configure
        make

    - name: Make Polyglot Book
      run: |
        ./polyglot/polyglot make-book \
          -pgn filtered_960_bots_2200plus.pgn \
          -bin book.bin \
          -max-ply 40 \
          -threads 16

    - name: Upload book.bin
      uses: actions/upload-artifact@v4
      with:
        name: chess960-book
        path: book.bin
