name: Build Polyglot Book

on:
  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Clone working Polyglot repo
      run: git clone https://github.com/ddugovic/polyglot.git

    - name: Build Polyglot from src
      run: |
        cd polyglot/src
        make

    - name: Generate book.bin
      run: |
        cd polyglot/src
        ./polyglot make-book ../../../filtered_960_bots_2200plus.pgn ../../../book.bin 40 16
        mv ../../../book.bin $GITHUB_WORKSPACE/

    - name: Upload book.bin
      uses: actions/upload-artifact@v4
      with:
        name: chess960-book
        path: book.bin
