name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  run-bot:
    runs-on: windows-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Python Dependency Installation
        uses: actions/checkout@v3

      - name: Injection For My Repo
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Stockfish
        run: chmod +x ./engines/stockfish

      - name: Run Bot
        run: python -u user_interface.py --matchmaking
