name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  

jobs:
  run-bot:
    runs-on: windows-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        run: |
          (Get-Content config.yml) -replace '^token:.*', "token: `"$env:TOKEN`"" | Set-Content config.yml
        shell: pwsh

      # Windows does not need chmod for exe files, so this step is removed.

      - name: Run Bot
        run: python -u user_interface.py --matchmaking
