name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Insert Token
        run: sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Download latest Stockfish Dev
        run: |
          curl -L -o stockfish.zip \
            http://abrok.eu/stockfish/latest/linux/stockfish_x64_modern.zip
          unzip -o stockfish.zip -d engines/
          chmod +x engines/stockfish

      - name: Fairy Stockfish
        run: chmod +x ./engines/fairy-stockfish

      - name: Run Bot
        run: python -u user_interface.py --matchmaking
