name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Python Dependency Installation
        uses: actions/checkout@v3

      - name: Injection For My Repo
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Insert Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml

      - name: Download latest Stockfish Dev
        run: |
          curl -L -o stockfish.zip "$(curl -s https://abrok.eu/stockfish/ | grep -E 'Linux x64 for modern computers.*\.zip' | head -n1 | sed -E 's/.*href="([^"]+)".*/\1/')"
          unzip -o stockfish.zip -d engines/
          chmod +x engines/stockfish

      - name: Fairy Stockfish
        run: chmod +x ./engines/fairy-stockfish

      - name: Run Bot
        run: python -u user_interface.py --matchmaking
