name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Insert Token into Config
        run: |
          if grep -q '^token:' config.yml; then
            sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml
          else
            echo "token: \"${TOKEN}\"" >> config.yml
          fi

      - name: Make Engines Executable
        run: |
          chmod +x ./engines/stockfish || true
          chmod +x ./engines/fairy-stockfish || true

      - name: Run Bot
        run: python -u user_interface.py --matchmaking
