name: Download Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  sync_syzygy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install jq
        run: sudo apt update && sudo apt install -y jq

      - name: Create syzygy directory
        run: mkdir -p engines/syzygy

      - name: Fetch file list from suprabot repo
        id: files
        run: |
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          curl -s https://api.github.com/repos/suprateem-ux/suprabot/contents/engines/syzygy \
            | jq -r '.[] | select(.type == "file") | .name' \
            >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Download each file
        run: |
          base="https://raw.githubusercontent.com/suprateem-ux/suprabot/main/engines/syzygy"
          mkdir -p engines/syzygy
          while read -r fname; do
            echo "Downloading $fname"
            curl -sSL "$base/$fname" -o "engines/syzygy/$fname"
          done <<< "${{ steps.files.outputs.files }}"

      - name: Track with Git LFS
        run: |
          git lfs track "engines/syzygy/*.rtbw"
          git lfs track "engines/syzygy/*.rtbz"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/syzygy .gitattributes
          git commit -m "Sync Suprabot Syzygy tablebases" || echo "Nothing to commit"
          git push
