Run cd engines/syzygy
Downloading KBBBvK.rtbw
Attempt 1 failed: KBBBvK.rtbw may be corrupt.
Attempt 2 failed: KBBBvK.rtbw may be corrupt.
Attempt 3 failed: KBBBvK.rtbw may be corrupt.
Skipping corrupt file: KBBBvK.rtbw
Downloading KBBNvK.rtbw
Attempt 1 failed: KBBNvK.rtbw may be corrupt.
Attempt 2 failed: KBBNvK.rtbw may be corrupt.
Attempt 3 failed: KBBNvK.rtbw may be corrupt.
Skipping corrupt file: KBBNvK.rtbw
Downloading KBBPvK.rtbw
Attempt 1 failed: KBBPvK.rtbw may be corrupt.
Attempt 2 failed: KBBPvK.rtbw may be corrupt.
Attempt 3 failed: KBBPvK.rtbw may be corrupt.
Skipping corrupt file: KBBPvK.rtbw
Downloading KBBvK.rtbw
Attempt 1 failed: KBBvK.rtbw may be corrupt.
Attempt 2 failed: KBBvK.rtbw may be corrupt.
Attempt 3 failed: KBBvK.rtbw may be corrupt.
Skipping corrupt file: KBBvK.rtbw
Downloading KBBvKB.rtbw
Attempt 1 failed: KBBvKB.rtbw may be corrupt.
Attempt 2 failed: KBBvKB.rtbw may be corrupt.
Attempt 3 failed: KBBvKB.rtbw may be corrupt.
Skipping corrupt file: KBBvKB.rtbw
Downloading KBBvKN.rtbw
Attempt 1 failed: KBBvKN.rtbw may be corrupt.
Attempt 2 failed: KBBvKN.rtbw may be corrupt.
Attempt 3 failed: KBBvKN.rtbw may be corrupt.
Skipping corrupt file: KBBvKN.rtbw
Downloading KBBvKP.rtbw
Attempt 1 failed: KBBvKP.rtbw may be corrupt.
Attempt 2 failed: KBBvKP.rtbw may be corrupt.
Attempt 3 failed: KBBvKP.rtbw may be corrupt.
Skipping corrupt file: KBBvKP.rtbw
