name: Upload Syzygy

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir -p engines/syzygy
          cd engines/syzygy

          # Download all WDL .rtbw files
          wget -r -l1 -nd -np -A "*.rtbw" https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl/

          # Download all DTZ .rtbz files
          wget -r -l1 -nd -np -A "*.rtbz" https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz/

          cd ../../

          git lfs track "engines/syzygy/*.rtbw"
          git lfs track "engines/syzygy/*.rtbz"
          git add engines/syzygy .gitattributes

          git diff --cached --quiet || (git commit -m "Add full Syzygy 3-4-5 WDL + DTZ" && git push)
