name: Download Syzygy

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create syzygy directory
        run: mkdir -p engines/syzygy

      - name: Download 3-4-5 WDL
        run: |
          cd engines/syzygy
          wget -r -np -nH --cut-dirs=4 -R "index.html*" https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl/

      - name: Download 3-4-5 DTZ
        run: |
          cd engines/syzygy
          wget -r -np -nH --cut-dirs=4 -R "index.html*" https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz/

      - name: Commit and push syzygy files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add engines/syzygy/*
          git commit -m "Add Syzygy 3-4-5 tablebases (WDL + DTZ)"
          git push
