name: Upload Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create engines/syzygy directory
        run: mkdir -p engines/syzygy

      - name: Download WDL (.rtbw) files
        run: |
          wget -r -np -nH --cut-dirs=3 --accept "*.rtbw" \
            https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl/ \
            -P engines/syzygy/

      - name: Download DTZ (.rtbz) files
        run: |
          wget -r -np -nH --cut-dirs=3 --accept "*.rtbz" \
            https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz/ \
            -P engines/syzygy/

      - name: Track files with Git LFS
        run: |
          git lfs track "engines/syzygy/*.rtbw"
          git lfs track "engines/syzygy/*.rtbz"
          echo "engines/syzygy/*.rtbw" >> .gitattributes
          echo "engines/syzygy/*.rtbz" >> .gitattributes

      - name: Commit and push
        run: |
          git add engines/syzygy .gitattributes
          git commit -m "Add Syzygy 3-4-5 WDL and DTZ tablebases"
          git push || echo "Nothing to push"
