name: Replace LFS with Normal Files in engines/syzygy/

on:
  workflow_dispatch:

jobs:
  convert-syzygy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo including LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Replace LFS files with actual binaries
        run: |
          echo "Looking for LFS-tracked files in engines/syzygy/..."
          git lfs ls-files -n | grep '^engines/syzygy/' > lfs_files.txt || true

          if [ -s lfs_files.txt ]; then
            while read file; do
              echo "Replacing $file with actual binary content"
              cp "$file" "$file.bak"
              git rm --cached "$file"
              mv "$file.bak" "$file"
              git add "$file"
            done < lfs_files.txt
            git commit -m "Replace LFS files in engines/syzygy/ with actual binaries"
          else
            echo "No LFS files found in engines/syzygy/"
          fi

      - name: Permanently untrack syzygy folder from LFS
        run: |
          git lfs untrack "engines/syzygy/*"
          git add .gitattributes
          git commit -m "Stop tracking syzygy files with LFS" || echo "Nothing to commit"

      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://$PAT_TOKEN@github.com/${{ github.repository }}
          git push origin HEAD:main --force

      - name: Cleanup temp file
        run: rm -f lfs_files.txt
