name: Download Syzygy

on:
  workflow_dispatch:

jobs:
  fetch-syzygy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: false   # Do NOT pull LFS pointers

      - name: Make syzygy directory
        run: mkdir -p engines/syzygy

      - name: Download Syzygy 3-4-5 WDL
        run: |
          wget -c -r -np -nH -nd -e robots=off \
          https://tablebase.lichess.ovh/tables/standard/3-4-5-wdl/ \
          -P engines/syzygy

      - name: Download Syzygy 3-4-5 DTZ
        run: |
          wget -c -r -np -nH -nd -e robots=off \
          https://tablebase.lichess.ovh/tables/standard/3-4-5-dtz/ \
          -P engines/syzygy

      - name: Verify files
        run: ls -lh engines/syzygy | head -20

      - name: Commit and push binaries
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add engines/syzygy
          git commit -m "Add full Syzygy tablebases (3-4-5)"
          git push
