name: Upload Syzygy

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          mkdir -p engines/syzygy
          cd engines/syzygy

          wget -nv https://tablebase.lichess.ovh/tables/3-4-5-wdl/KQvK.rtbw
          wget -nv https://tablebase.lichess.ovh/tables/3-4-5-wdl/KQvKP.rtbw

          wget -nv https://tablebase.lichess.ovh/tables/3-4-5-dtz/KQvK.rtbz
          wget -nv https://tablebase.lichess.ovh/tables/3-4-5-dtz/KQvKP.rtbz

          cd ../../

          git lfs track "engines/syzygy/*.rtbw"
          git lfs track "engines/syzygy/*.rtbz"
          git add engines/syzygy .gitattributes
          git commit -m "Add Syzygy WDL & DTZ files"
          git push
