name: Upload Syzygy Tablebases

on:
  workflow_dispatch:

jobs:
  syzygy-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Create syzygy folder and download WDL & DTZ files
        run: |
          mkdir -p engines/syzygy
          cd engines/syzygy
          wget https://tablebase.lichess.ovh/tables/3-4-5-wdl/KQvK.rtbw
          wget https://tablebase.lichess.ovh/tables/3-4-5-wdl/KRvKN.rtbw
          wget https://tablebase.lichess.ovh/tables/3-4-5-wdl/KQvKP.rtbw
          wget https://tablebase.lichess.ovh/tables/3-4-5-dtz/KQvK.rtbz
          wget https://tablebase.lichess.ovh/tables/3-4-5-dtz/KRvKN.rtbz
          wget https://tablebase.lichess.ovh/tables/3-4-5-dtz/KQvKP.rtbz

      - name: Track with Git LFS
        run: |
          git lfs track "engines/syzygy/*.rtbw"
          git lfs track "engines/syzygy/*.rtbz"

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .gitattributes
          git add engines/syzygy
          git commit -m "Add Syzygy WDL and DTZ files"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
